### PR TITLE
Fix RuntimeException while restoring a saved game

### PR DESCRIPTION
**Pull request by allyourcodearebelongtous**
As suggested by mateijcik EventTable.java does not call callEvent() while deserializing. Savegame.java actually wasn't changed (it got caught in this PR because I made some changes and reverted them with this commit).
Corresponding Issue is #8

### CODE REVIEW

**Comment by bekuno** [comment]
@allyourcodearebelongtous 
Thanks for your work.

Please ignore for now the Codacy review. If you want to change some of the points of them the please create an other PR.

Some hints for you.
It is not necessary to close and reopen a PR, if it is not ready yet. You can name it "WIP" in the title. I set the state now as label. 

You can reopen a PR, if necessary. You need not to create a new one.

Please use a dedicated branch for a PR. Then you can left master and release acording to the master/release at upstream. You have an instruction at https://github.com/cgeo/cgeo/wiki/git-beginners and https://github.com/cgeo/WhereYouGo/pull/45#issuecomment-591056162.

**Comment by allyourcodearebelongtous** [comment]
@bekuno
Thanks for the links. I'll try to remember that next time. 
My next steps will be: work on the "actual correct fix" as described by matejcik. Until then the supposed quick fix will have to suffice.

**Comment by allyourcodearebelongtous** [comment]
I created a branch "restorefix" in my fork of openWIG for testing. In this branch I implemented the " slightly better fix" from matejcik, released it as v0.0.1-alpha and changed build.gradle to

```
    // openwig with extentions
    implementation 'com.github.allyourcodearebelongtous:openwig:v0.0.1-alpha'
```

So I understand there is no need to build a jar file from cgeo:openWIG which is quite nice.

The Crash.urwigo example cartrige from [issue #8](https://github.com/cgeo/openWIG/issues/8#issuecomment-610492272) does run fine now when restoring a saved game. 

I think this PR should be considered a working fix for the problem and not WIP any more.

What to do now? Keep this PR and merge it into master after approval by some other testers? Switch from this PR to the changes in branch "restorefix"? 

I'd say keep it simple and merge from here if all is fine. I'll use "restorefix" for the "**actual correct**" fix (implement _deserialize()_ in all subclasses of **EventTable.java** and use _Engine.instance.savegame.restoreValue(in, table);_ in **EventTable.java**). But this could take a while, 'm afraid.

@bekuno 
What do you suggest? Removing WIP from this PR or close this PR and create a (identical) PR in  the "restorefix" branch?

**Comment by bekuno** [comment]
>     implementation 'com.github.allyourcodearebelongtous:openwig:v0.0.1-alpha'

You can refer to the sort commit number, here `implementation 'com.github.allyourcodearebelongtous:openwig:65ed320`
No need for a release.

I would suggest (if possible) to use a dedicated branch. But it is not necessary.
Other advantage could be that you can in this way squash your changes to one commit.

The PR wants to change the complete content for both files.
Maybe the line ending format is changed?

Before merging your PR I want to solve Issue #3 first. 
Therefore I let the WIP label for now.

**Comment by allyourcodearebelongtous** [comment]
Agreed, no need to be hasty.

**Comment by allyourcodearebelongtous** [comment]
@bekuno Maybe it's time to merge the PR now? @Lineflyer posted an issue (https://github.com/cgeo/WhereYouGo/issues/367) in WhereYouGo that could be solved with this workaround.

**Comment by bekuno** [comment]
@allyourcodearebelongtous 

The big problem with analysing your changes is that your PR tries to replace the entire content of the two files.
This is not good and should be improved.

I checked your changes in my branch and in the second file (savegame.java) I only found changes in the formatting. This does not belong in this PR.

An easy way would be to create a new branch, copy your changes to the file(s) from GitHub to your local files and create a new PR.

**Comment by allyourcodearebelongtous** [comment]
Never mind. It's been a while and therefor I'll close this PR. After forking a new branch I'll test again.

**Pull request closed without merging**
